---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

# Reading in datasets
tmdb_credits <- read_csv("tmdb_5000_credits.csv")
tmdb_movies <- read_csv("tmdb_5000_movies.csv")

```

```{r}

# Selecting title, runtime and budget columns and calculating the number of
# "NA" values
movies_selected <- tmdb_movies %>% 
  select(original_title, runtime, budget) %>%
  summarise(org_title_mv = sum(is.na(title)),
            runtime_mv = sum(is.na(runtime)),
            budget_mv = sum(is.na(budget)))

# Output number of NA values found in dataset for the columns stated above
movies_selected

```

```{r}

# Alternative method for calculating number of NA values across the same
# headings
movies_selected <- tmdb_movies %>% 
  select(original_title, runtime, budget) %>%
  summarise(across(.fns = ~sum(is.na(.x))))

movies_selected
```


```{r}

# Replacing zero runtime values with NA
movies_runtime <- tmdb_movies %>%
  select(title, runtime, budget) %>% 
  mutate(runtime = na_if(runtime, 0))
  
# Calculating the number of NA values in the runtime column
movies_runtime %>% 
  summarise(num_na = sum(is.na(runtime)))

```

```{r}

# Replace NA values in 'runtime' column with median runtime
movies_imputed <- movies_runtime %>% 
  mutate(runtime = coalesce(runtime, median(runtime, na.rm = T)))

# Check for no missing runtime values
movies_imputed %>% 
  summarise(runtime_mv = sum(is.na(runtime)))

```

```{r}

# Finding the top 10 longest runtimes
longest_runtimes <- movies_imputed %>%
  slice_max(runtime, n = 10)



# Finding the top 10 shortest runtimes
shortest_runtimes <- movies_imputed %>%
  slice_min(runtime, n = 10)

# Output longest and shortest runtimes
longest_runtimes
shortest_runtimes


```

```{r}

# Change small budget values to the median value
movies_imputed <- movies_imputed %>% 
  mutate(budget1 = if_else(budget < 100, median(budget, na.rm = T),budget)) %>% 
  arrange(runtime)

movies_imputed
```

#### EXTENSION HOMEWORK

```{r}

# Create additional column identifying type of budget based on budget value
movie_budgets <- movies_runtime %>% 
  mutate(budget_type = case_when(budget < 12e6 ~ "Small Budget",
                                 budget < 4e7  ~ "Medium Budget",
                                 TRUE          ~ "Big Budget"))

movie_budgets
```

```{r}
# Finding the number of NA values across all columns of the dataset.
num_of_na <- tmdb_movies %>%
  mutate(across(where(is.character),is.na),
         across(where(is.numeric),is.na)) %>%
  summarise(across(where(is.logical),sum))

num_of_na

## alternative using across function with multiple logical expressions (sum & is.na)
tmdb_movies %>% 
  summarise(across(where(is.numeric), ~sum(is.na(.x))),
            across(where(is.character), ~sum(is.na(.x))))
         
```

